### ISSUE TITLE
[INFO] what IDE?

### ISSUE THREAD

**Issue by karamo** [Affirmatech/MeshSense#20]
Can you please provide more information on how to set up the development environment for MeshSense?

**Comment by Soltares** [comment]
Definitely.  I will update the README hopefully soon with development details.  Thank you for your interest!

**Comment by Soltares** [comment]
The README has been updated with development setup.  Specifically which IDE is up to you, but I have had good experiences with VSCode and it's Svelte and Tailwind extensions.  If you need any additional information just let me know.

**Comment by Soltares** [comment]
Closing for now unless any issues arise regarding development setup.
