### ISSUE TITLE
[Feature] Remember last map position and zoom view - dont reset/default back to North America

### ISSUE THREAD

**Issue by Talie5in** [Affirmatech/MeshSense#27]
Remember last map position and zoom view - dont reset/default back to North America

This is annoying to come back to a machine and its looking at North America, or when re-opening the app, default backs to North America.

Store last view and return on app start etc.

**Comment by Soltares** [comment]
That is an excellent suggestion, thanks!  By default it will center on the position of the connected node, but if that is not available it zooms out to North America.  Reloading last position instead makes a lot of sense.

**Comment by Soupbones** [comment]
I came here to say this exact thing as I just started usnig this awesome app to monitor my local mesh. Its dam annoying to have to find your node location every time you restart the app. If your node had a location then the app shoudl automatically start there on the map. I would also like to see messaging done better, maybe a window or a tab for messages from nodes you are communication with.

**Comment by Soltares** [comment]
Thanks @Soupbones for the feedback!  The latest beta `v1.0.16-beta.1` should have the map position save feature if you wanted to check it out.  Simply enable Beta Updates inside of settings.  Thanks!

**Comment by Soupbones** [comment]
> Thanks @Soupbones for the feedback! The latest beta `v1.0.16-beta.1` should have the map position save feature if you wanted to check it out. Simply enable Beta Updates inside of settings. Thanks!

Great to get such a quick reply. Not often you see open source developers working to fix things so quick. I commend you!
 That said, the update feature worked great. I very quickly had the new beta installed. Alas, now I have no map. The map doesnt seem to be loading at all now.  I may have to uninstall to roll it back. Using Windows 11.

**Comment by Soltares** [comment]
> The map doesnt seem to be loading at all now.

I have seen this happen very rarely, but usually a reconnect or application restart will resolve the issue.  The map does require internet access to download the tiles.

**Comment by Soltares** [comment]
Closing at the requested feature has been released in `v1.0.16`

**Comment by Soupbones** [comment]
I did that. Restart several times, reinstall. Still did it. Gave up, went
back to previous version. My PC has working internet.
