### ISSUE TITLE
Feature Request: Allow user to determine/set time-frame threshold for active vs inactive timer

### ISSUE THREAD

**Issue by mblauser** [Affirmatech/MeshSense#3]
The default inactivity time-frame for nodes is hard-set at 60 minutes.  Allow the user to increase or decrease this inactivity timer in minutes or hours, potentially keeping nodes visible in the node list and map for longer or shorter periods of time.

Some nodes are set to broadcast their identity, telemetry, and position less frequently than 1 hour.  The map and node list currently flag these nodes as inactive when in fact the node remains active and reachable if queried.

**Comment by Soltares** [comment]
Finished implementation in b7859b9a
