### ISSUE TITLE
Error installing under Linux

### ISSUE THREAD

**Issue by mdede439** [Affirmatech/MeshSense#30]
I am attempting to install MeshSense on a Debian VM on Proxmox and I am running into an error when I run  ./update.mjs.  It returns and error 

import { styleText } from 'util';
SyntaxError: The requested module 'util' does not provide an export named 'styleText'

Have you run into this?  Where is module 'util'?

**Comment by mdede439** [comment]
I figured out my issue.  I had no idea what a .mjs file was.  after figuring out that, it turns out I installed too low a version of Node.js.  Got it installed now.

**Comment by mdede439** [comment]
I figured out my issue. I had no idea what a .mjs file was. after figuring out that, it turns out I installed too low a version of Node.js. Got it installed now.

**Comment by mdede439** [comment]
I figured out my issue. I had no idea what a .mjs file was. after figuring out that, it turns out I installed too low a version of Node.js. Got it installed now.

**Comment by mikecarper** [comment]
```
node -v
npm -v
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
node -v
npm -v
```
